<?php
/**
 * Регистрация ACF полей для секции "Procedura de aplicare"
 * (Процедура подачи заявки)
 *
 * Создано для БЕСПЛАТНОЙ версии ACF.
 * Использует индивидуальные поля для каждого шага, так как Repeater Field
 * требует ACF PRO и может вызвать проблемы с подполями.
 * Все поля имеют default_value.
 */
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_application_procedure_left_block', // Уникальный ключ для группы полей
    'title' => 'Procedura (левый блок)', // Название группы полей в админке WP
    'fields' => array(
        // --- Основной заголовок и описание секции ---
        array(
            'key' => 'field_ap_main_title_heading',
            'label' => 'Основной заголовок и описание секции',
            'name' => '', // Поле типа "Сообщение" не требует имени
            'type' => 'message',
            'message' => 'Настройте главный заголовок и вступительный текст секции "Procedura de aplicare".',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_main_title',
            'label' => 'Основной заголовок',
            'name' => 'ap_main_title',
            'type' => 'text',
            'instructions' => 'Введите главный заголовок секции.',
            'required' => 0,
            'default_value' => 'Procedura de aplicare',
            'placeholder' => 'Procedura de aplicare',
        ),
        array(
            'key' => 'field_ap_main_description',
            'label' => 'Основное описание',
            'name' => 'ap_main_description',
            'type' => 'textarea',
            'instructions' => 'Введите вступительный текст секции.',
            'required' => 0,
            'rows' => 3,
            'new_lines' => 'wpautop', // Преобразует переносы строк в <p> и <br>
            'default_value' => 'Procesul de aplicare are loc în 8 pași simpli și transparenți, fiecare cu cerințe specifice și termene definite.',
            'placeholder' => 'Процесс подачи заявки состоит из 8 простых и прозрачных шагов...',
        ),

        // --- Шаг 1 ---
        array(
            'key' => 'field_ap_step1_heading',
            'label' => 'Шаг 1: Verifică dacă ești eligibil',
            'name' => '',
            'type' => 'message',
            'message' => 'Настройте содержимое для Шага 1.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step1_title',
            'label' => 'Шаг 1: Заголовок',
            'name' => 'ap_step1_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Verifică dacă ești eligibil',
            'placeholder' => 'Проверьте, соответствуете ли вы требованиям',
        ),
        array(
            'key' => 'field_ap_step1_description',
            'label' => 'Шаг 1: Описание',
            'name' => 'ap_step1_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Înainte de orice, asigură-te că proiectul tău se încadrează într-unul dintre sectoarele eligibile și că respecți condițiile de bază (investiție nouă, valoare minimă, etc.).',
            'placeholder' => 'Прежде всего, убедитесь, что ваш проект соответствует одному из подходящих секторов...',
        ),
        array(
            'key' => 'field_ap_step1_note_label',
            'label' => 'Шаг 1: Метка примечания',
            'name' => 'ap_step1_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Recomandare:',
            'placeholder' => 'Рекомендация:',
        ),
        array(
            'key' => 'field_ap_step1_note_text',
            'label' => 'Шаг 1: Текст примечания',
            'name' => 'ap_step1_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Consultă criteriile de eligibilitate și sectoarele prioritare',
            'placeholder' => 'Ознакомьтесь с критериями приемлемости и приоритетными секторами',
        ),

        // --- Шаг 2 ---
        array(
            'key' => 'field_ap_step2_heading',
            'label' => 'Шаг 2: Pregătește dosarul și depune cererea',
            'name' => '',
            'type' => 'message',
            'message' => 'Настройте содержимое для Шага 2.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step2_title',
            'label' => 'Шаг 2: Заголовок',
            'name' => 'ap_step2_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Pregătește dosarul și depune cererea',
            'placeholder' => 'Подготовьте досье и подайте заявку',
        ),
        array(
            'key' => 'field_ap_step2_description',
            'label' => 'Шаг 2: Описание',
            'name' => 'ap_step2_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Completezi cererea de finanțare și o trimiți către Minister, împreună cu planul de afaceri și documentele necesare.',
            'placeholder' => 'Заполните заявку на финансирование и отправьте ее в Министерство...',
        ),
        array(
            'key' => 'field_ap_step2_note_label',
            'label' => 'Шаг 2: Метка примечания',
            'name' => 'ap_step2_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Documente:',
            'placeholder' => 'Документы:',
        ),
        array(
            'key' => 'field_ap_step2_note_text',
            'label' => 'Шаг 2: Текст примечания',
            'name' => 'ap_step2_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Cerere, plan de afaceri, documente legale și financiare',
            'placeholder' => 'Заявление, бизнес-план, юридические и финансовые документы',
        ),

        // --- Шаг 3 ---
        array(
            'key' => 'field_ap_step3_heading',
            'label' => 'Шаг 3: Primești un răspuns preliminar',
            'name' => '',
            'type' => 'message',
            'message' => 'Настройте содержимое для Шага 3.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step3_title',
            'label' => 'Шаг 3: Заголовок',
            'name' => 'ap_step3_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Primești un răspuns preliminar',
            'placeholder' => 'Получаете предварительный ответ',
        ),
        array(
            'key' => 'field_ap_step3_description',
            'label' => 'Шаг 3: Описание',
            'name' => 'ap_step3_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'În maximum 10 zile lucrătoare, afli dacă dosarul tău este complet și corect sau dacă trebuie completări.',
            'placeholder' => 'В течение максимум 10 рабочих дней вы узнаете, является ли ваше досье полным...',
        ),
        array(
            'key' => 'field_ap_step3_note_label',
            'label' => 'Шаг 3: Метка примечания',
            'name' => 'ap_step3_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Termen:',
            'placeholder' => 'Срок:',
        ),
        array(
            'key' => 'field_ap_step3_note_text',
            'label' => 'Шаг 3: Текст примечания',
            'name' => 'ap_step3_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Maximum 10 zile lucrătoare',
            'placeholder' => 'Максимум 10 рабочих дней',
        ),

        // --- Шаг 4 ---
        array(
            'key' => 'field_ap_step4_heading',
            'label' => 'Шаг 4: Evaluare finală',
            'name' => '',
            'type' => 'message',
            'message' => 'Настройте содержимое для Шага 4.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step4_title',
            'label' => 'Шаг 4: Заголовок',
            'name' => 'ap_step4_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Evaluare finală',
            'placeholder' => 'Окончательная оценка',
        ),
        array(
            'key' => 'field_ap_step4_description',
            'label' => 'Шаг 4: Описание',
            'name' => 'ap_step4_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Un comitet interinstituțional analizează în detaliu proiectul și decide dacă primești sprijinul.',
            'placeholder' => 'Межведомственный комитет детально анализирует проект...',
        ),
        array(
            'key' => 'field_ap_step4_note_label',
            'label' => 'Шаг 4: Метка примечания',
            'name' => 'ap_step4_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Evaluare:',
            'placeholder' => 'Оценка:',
        ),
        array(
            'key' => 'field_ap_step4_note_text',
            'label' => 'Шаг 4: Текст примечания',
            'name' => 'ap_step4_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Viabilitate tehnică, economică și impact asupra economiei',
            'placeholder' => 'Техническая, экономическая жизнеспособность и влияние на экономику',
        ),

        // --- Шаг 5 ---
        array(
            'key' => 'field_ap_step5_heading',
            'label' => 'Шаг 5: Semnezi contractul',
            'name' => '',
            'type' => 'message',
            'message' => 'Настройте содержимое для Шага 5.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step5_title',
            'label' => 'Шаг 5: Заголовок',
            'name' => 'ap_step5_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Semnezi contractul',
            'placeholder' => 'Подписываете контракт',
        ),
        array(
            'key' => 'field_ap_step5_description',
            'label' => 'Шаг 5: Описание',
            'name' => 'ap_step5_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Dacă proiectul este aprobat, semnezi contractul de finanțare cu ministerul.',
            'placeholder' => 'Если проект одобрен, вы подписываете договор о финансировании с министерством.',
        ),
        array(
            'key' => 'field_ap_step5_note_label',
            'label' => 'Шаг 5: Метка примечания',
            'name' => 'ap_step5_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Contract:',
            'placeholder' => 'Контракт:',
        ),
        array(
            'key' => 'field_ap_step5_note_text',
            'label' => 'Шаг 5: Текст примечания',
            'name' => 'ap_step5_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Specificarea obligațiilor, termenelor și modalităților',
            'placeholder' => 'Указание обязательств, сроков и условий',
        ),

        // --- Шаг 6 ---
        array(
            'key' => 'field_ap_step6_heading',
            'label' => 'Шаг 6: Demonstrezi contribuția ta',
            'name' => '',
            'type' => 'message',
            'message' => 'Настройте содержимое для Шага 6.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step6_title',
            'label' => 'Шаг 6: Заголовок',
            'name' => 'ap_step6_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Demonstrezi contribuția ta',
            'placeholder' => 'Демонстрируете свой вклад',
        ),
        array(
            'key' => 'field_ap_step6_description',
            'label' => 'Шаг 6: Описание',
            'name' => 'ap_step6_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Trebuie să ai cel puțin 25% din investiție acoperită din surse proprii sau dintr-un alt finanțator.',
            'placeholder' => 'Вы должны иметь не менее 25% инвестиций, покрытых за счет собственных средств...',
        ),
        array(
            'key' => 'field_ap_step6_note_label',
            'label' => 'Шаг 6: Метка примечания',
            'name' => 'ap_step6_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Cofinanțare:',
            'placeholder' => 'Софинансирование:',
        ),
        array(
            'key' => 'field_ap_step6_note_text',
            'label' => 'Шаг 6: Текст примечания',
            'name' => 'ap_step6_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Minimum 25% contribuție proprie obligatorie',
            'placeholder' => 'Минимум 25% обязательного собственного вклада',
        ),

        // --- Шаг 7 ---
        array(
            'key' => 'field_ap_step7_heading',
            'label' => 'Шаг 7: Primești sprijinul financiar',
            'name' => '',
            'type' => 'message',
            'message' => 'Настройте содержимое для Шага 7.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step7_title',
            'label' => 'Шаг 7: Заголовок',
            'name' => 'ap_step7_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Primești sprijinul financiar',
            'placeholder' => 'Получаете финансовую поддержку',
        ),
        array(
            'key' => 'field_ap_step7_description',
            'label' => 'Шаг 7: Описание',
            'name' => 'ap_step7_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Ajutorul vine sub formă de grant (25%) și scutiri fiscale (75%), conform unui plan de plată agreat.',
            'placeholder' => 'Помощь предоставляется в виде гранта (25%) и налоговых льгот (75%)...',
        ),
        array(
            'key' => 'field_ap_step7_note_label',
            'label' => 'Шаг 7: Метка примечания',
            'name' => 'ap_step7_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Structura:',
            'placeholder' => 'Структура:',
        ),
        array(
            'key' => 'field_ap_step7_note_text',
            'label' => 'Шаг 7: Текст примечания',
            'name' => 'ap_step7_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => '25% grant nerambursabil + 75% facilitate fiscală',
            'placeholder' => '25% невозвратный грант + 75% налоговая льгота',
        ),

        // --- Шаг 8 ---
        array(
            'key' => 'field_ap_step8_heading',
            'label' => 'Шаг 8: Rămâi în contact și respecți angajamentele',
            'name' => '',
            'type' => 'message',
            'message' => 'Настройте содержимое для Шага 8.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step8_title',
            'label' => 'Шаг 8: Заголовок',
            'name' => 'ap_step8_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Rămâi în contact și respecți angajamentele',
            'placeholder' => 'Оставайтесь на связи и соблюдайте обязательства',
        ),
        array(
            'key' => 'field_ap_step8_description',
            'label' => 'Шаг 8: Описание',
            'name' => 'ap_step8_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Ministerul verifică periodic dacă proiectul funcționează conform planului. Investiția trebuie menținută activă timp de 3 ani (IMM) sau 5 ani (întreprinderi mari).',
            'placeholder' => 'Министерство периодически проверяет, функционирует ли проект...',
        ),
        array(
            'key' => 'field_ap_step8_note_label',
            'label' => 'Шаг 8: Метка примечания',
            'name' => 'ap_step8_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Monitorizare:',
            'placeholder' => 'Мониторинг:',
        ),
        array(
            'key' => 'field_ap_step8_note_text',
            'label' => 'Шаг 8: Текст примечания',
            'name' => 'ap_step8_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Rapoarte periodice și vizite de verificare',
            'placeholder' => 'Периодические отчеты и проверочные визиты',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'page', // Показать на всех страницах по умолчанию. Настройте по необходимости.
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Поля для секции "Процедура подачи заявки" (левый блок) на странице.',
));

endif;
?>
