
<?php
/**
 * Înregistrează câmpurile ACF pentru secțiunea "Procedura de aplicare"
 * (Procedura de aplicare)
 *
 * Creat pentru versiunea GRATUITĂ a ACF.
 * Utilizează câmpuri individuale pentru fiecare pas, deoarece Repeater Field
 * necesită ACF PRO și poate cauza probleme cu subcâmpurile.
 * Toate câmpurile au default_value.
 */
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_application_procedure_left_block', // Cheie unică pentru grupul de câmpuri
    'title' => 'Procedura (bloc stânga)', // Titlul grupului de câmpuri în panoul de administrare WP
    'fields' => array(
        // --- Titlul principal și descrierea secțiunii ---
        array(
            'key' => 'field_ap_main_title_heading',
            'label' => 'Titlul principal și descrierea secțiunii',
            'name' => '', // Câmpul de tip "Mesaj" nu necesită un nume
            'type' => 'message',
            'message' => 'Configurați titlul principal și textul introductiv al secțiunii "Procedura de aplicare".',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_main_title',
            'label' => 'Titlul principal',
            'name' => 'ap_main_title',
            'type' => 'text',
            'instructions' => 'Introduceți titlul principal al secțiunii.',
            'required' => 0,
            'default_value' => 'Procedura de aplicare',
            'placeholder' => 'Procedura de aplicare',
        ),
        array(
            'key' => 'field_ap_main_description',
            'label' => 'Descrierea principală',
            'name' => 'ap_main_description',
            'type' => 'textarea',
            'instructions' => 'Introduceți textul introductiv al secțiunii.',
            'required' => 0,
            'rows' => 3,
            'new_lines' => 'wpautop', // Convertește rândurile noi în <p> și <br>
            'default_value' => 'Procesul de aplicare are loc în 8 pași simpli și transparenți, fiecare cu cerințe specifice și termene definite.',
            'placeholder' => 'Procesul de aplicare constă în 8 pași simpli și transparenți...',
        ),

        // --- Pasul 1 ---
        array(
            'key' => 'field_ap_step1_heading',
            'label' => 'Pasul 1: Verifică dacă ești eligibil',
            'name' => '',
            'type' => 'message',
            'message' => 'Configurați conținutul pentru Pasul 1.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step1_title',
            'label' => 'Pasul 1: Titlu',
            'name' => 'ap_step1_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Verifică dacă ești eligibil',
            'placeholder' => 'Verifică dacă ești eligibil',
        ),
        array(
            'key' => 'field_ap_step1_description',
            'label' => 'Pasul 1: Descriere',
            'name' => 'ap_step1_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Înainte de orice, asigură-te că proiectul tău se încadrează într-unul dintre sectoarele eligibile și că respecți condițiile de bază (investiție nouă, valoare minimă, etc.).',
            'placeholder' => 'Înainte de toate, asigură-te că proiectul tău se încadrează într-unul dintre sectoarele eligibile...',
        ),
        array(
            'key' => 'field_ap_step1_note_label',
            'label' => 'Pasul 1: Etichetă notă',
            'name' => 'ap_step1_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Recomandare:',
            'placeholder' => 'Recomandare:',
        ),
        array(
            'key' => 'field_ap_step1_note_text',
            'label' => 'Pasul 1: Text notă',
            'name' => 'ap_step1_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Consultă criteriile de eligibilitate și sectoarele prioritare',
            'placeholder' => 'Consultă criteriile de eligibilitate și sectoarele prioritare',
        ),

        // --- Pasul 2 ---
        array(
            'key' => 'field_ap_step2_heading',
            'label' => 'Pasul 2: Pregătește dosarul și depune cererea',
            'name' => '',
            'type' => 'message',
            'message' => 'Configurați conținutul pentru Pasul 2.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step2_title',
            'label' => 'Pasul 2: Titlu',
            'name' => 'ap_step2_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Pregătește dosarul și depune cererea',
            'placeholder' => 'Pregătește dosarul și depune cererea',
        ),
        array(
            'key' => 'field_ap_step2_description',
            'label' => 'Pasul 2: Descriere',
            'name' => 'ap_step2_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Completezi cererea de finanțare și o trimiți către Minister, împreună cu planul de afaceri și documentele necesare.',
            'placeholder' => 'Completezi cererea de finanțare și o trimiți către Minister...',
        ),
        array(
            'key' => 'field_ap_step2_note_label',
            'label' => 'Pasul 2: Etichetă notă',
            'name' => 'ap_step2_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Documente:',
            'placeholder' => 'Documente:',
        ),
        array(
            'key' => 'field_ap_step2_note_text',
            'label' => 'Pasul 2: Text notă',
            'name' => 'ap_step2_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Cerere, plan de afaceri, documente legale și financiare',
            'placeholder' => 'Cerere, plan de afaceri, documente legale și financiare',
        ),

        // --- Pasul 3 ---
        array(
            'key' => 'field_ap_step3_heading',
            'label' => 'Pasul 3: Primești un răspuns preliminar',
            'name' => '',
            'type' => 'message',
            'message' => 'Configurați conținutul pentru Pasul 3.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step3_title',
            'label' => 'Pasul 3: Titlu',
            'name' => 'ap_step3_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Primești un răspuns preliminar',
            'placeholder' => 'Primești un răspuns preliminar',
        ),
        array(
            'key' => 'field_ap_step3_description',
            'label' => 'Pasul 3: Descriere',
            'name' => 'ap_step3_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'În maximum 10 zile lucrătoare, afli dacă dosarul tău este complet și corect sau dacă trebuie completări.',
            'placeholder' => 'În maximum 10 zile lucrătoare, afli dacă dosarul tău este complet...',
        ),
        array(
            'key' => 'field_ap_step3_note_label',
            'label' => 'Pasul 3: Etichetă notă',
            'name' => 'ap_step3_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Termen:',
            'placeholder' => 'Termen:',
        ),
        array(
            'key' => 'field_ap_step3_note_text',
            'label' => 'Pasul 3: Text notă',
            'name' => 'ap_step3_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Maximum 10 zile lucrătoare',
            'placeholder' => 'Maximum 10 zile lucrătoare',
        ),

        // --- Pasul 4 ---
        array(
            'key' => 'field_ap_step4_heading',
            'label' => 'Pasul 4: Evaluare finală',
            'name' => '',
            'type' => 'message',
            'message' => 'Configurați conținutul pentru Pasul 4.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step4_title',
            'label' => 'Pasul 4: Titlu',
            'name' => 'ap_step4_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Evaluare finală',
            'placeholder' => 'Evaluare finală',
        ),
        array(
            'key' => 'field_ap_step4_description',
            'label' => 'Pasul 4: Descriere',
            'name' => 'ap_step4_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Un comitet interinstituțional analizează în detaliu proiectul și decide dacă primești sprijinul.',
            'placeholder' => 'Un comitet interinstituțional analizează în detaliu proiectul...',
        ),
        array(
            'key' => 'field_ap_step4_note_label',
            'label' => 'Pasul 4: Etichetă notă',
            'name' => 'ap_step4_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Evaluare:',
            'placeholder' => 'Evaluare:',
        ),
        array(
            'key' => 'field_ap_step4_note_text',
            'label' => 'Pasul 4: Text notă',
            'name' => 'ap_step4_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Viabilitate tehnică, economică și impact asupra economiei',
            'placeholder' => 'Viabilitate tehnică, economică și impact asupra economiei',
        ),

        // --- Pasul 5 ---
        array(
            'key' => 'field_ap_step5_heading',
            'label' => 'Pasul 5: Semnezi contractul',
            'name' => '',
            'type' => 'message',
            'message' => 'Configurați conținutul pentru Pasul 5.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step5_title',
            'label' => 'Pasul 5: Titlu',
            'name' => 'ap_step5_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Semnezi contractul',
            'placeholder' => 'Semnezi contractul',
        ),
        array(
            'key' => 'field_ap_step5_description',
            'label' => 'Pasul 5: Descriere',
            'name' => 'ap_step5_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Dacă proiectul este aprobat, semnezi contractul de finanțare cu ministerul.',
            'placeholder' => 'Dacă proiectul este aprobat, semnezi contractul de finanțare cu ministerul.',
        ),
        array(
            'key' => 'field_ap_step5_note_label',
            'label' => 'Pasul 5: Etichetă notă',
            'name' => 'ap_step5_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Contract:',
            'placeholder' => 'Contract:',
        ),
        array(
            'key' => 'field_ap_step5_note_text',
            'label' => 'Pasul 5: Text notă',
            'name' => 'ap_step5_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Specificarea obligațiilor, termenelor și modalităților',
            'placeholder' => 'Specificarea obligațiilor, termenelor și modalităților',
        ),

        // --- Pasul 6 ---
        array(
            'key' => 'field_ap_step6_heading',
            'label' => 'Pasul 6: Demonstrezi contribuția ta',
            'name' => '',
            'type' => 'message',
            'message' => 'Configurați conținutul pentru Pasul 6.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step6_title',
            'label' => 'Pasul 6: Titlu',
            'name' => 'ap_step6_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Demonstrezi contribuția ta',
            'placeholder' => 'Demonstrezi contribuția ta',
        ),
        array(
            'key' => 'field_ap_step6_description',
            'label' => 'Pasul 6: Descriere',
            'name' => 'ap_step6_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Trebuie să ai cel puțin 25% din investiție acoperită din surse proprii sau dintr-un alt finanțator.',
            'placeholder' => 'Trebuie să ai cel puțin 25% din investiție acoperită din surse proprii...',
        ),
        array(
            'key' => 'field_ap_step6_note_label',
            'label' => 'Pasul 6: Etichetă notă',
            'name' => 'ap_step6_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Cofinanțare:',
            'placeholder' => 'Cofinanțare:',
        ),
        array(
            'key' => 'field_ap_step6_note_text',
            'label' => 'Pasul 6: Text notă',
            'name' => 'ap_step6_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Minimum 25% contribuție proprie obligatorie',
            'placeholder' => 'Minimum 25% contribuție proprie obligatorie',
        ),

        // --- Pasul 7 ---
        array(
            'key' => 'field_ap_step7_heading',
            'label' => 'Pasul 7: Primești sprijinul financiar',
            'name' => '',
            'type' => 'message',
            'message' => 'Configurați conținutul pentru Pasul 7.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step7_title',
            'label' => 'Pasul 7: Titlu',
            'name' => 'ap_step7_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Primești sprijinul financiar',
            'placeholder' => 'Primești sprijinul financiar',
        ),
        array(
            'key' => 'field_ap_step7_description',
            'label' => 'Pasul 7: Descriere',
            'name' => 'ap_step7_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Ajutorul vine sub formă de grant (25%) și scutiri fiscale (75%), conform unui plan de plată agreat.',
            'placeholder' => 'Ajutorul vine sub formă de grant (25%) și scutiri fiscale (75%)...',
        ),
        array(
            'key' => 'field_ap_step7_note_label',
            'label' => 'Pasul 7: Etichetă notă',
            'name' => 'ap_step7_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Structura:',
            'placeholder' => 'Structura:',
        ),
        array(
            'key' => 'field_ap_step7_note_text',
            'label' => 'Pasul 7: Text notă',
            'name' => 'ap_step7_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => '25% grant nerambursabil + 75% facilitate fiscală',
            'placeholder' => '25% grant nerambursabil + 75% facilitate fiscală',
        ),

        // --- Pasul 8 ---
        array(
            'key' => 'field_ap_step8_heading',
            'label' => 'Pasul 8: Rămâi în contact și respecți angajamentele',
            'name' => '',
            'type' => 'message',
            'message' => 'Configurați conținutul pentru Pasul 8.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ap_step8_title',
            'label' => 'Pasul 8: Titlu',
            'name' => 'ap_step8_title',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Rămâi în contact și respecți angajamentele',
            'placeholder' => 'Rămâi în contact și respecți angajamentele',
        ),
        array(
            'key' => 'field_ap_step8_description',
            'label' => 'Pasul 8: Descriere',
            'name' => 'ap_step8_description',
            'type' => 'textarea',
            'rows' => 3,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Ministerul verifică periodic dacă proiectul funcționează conform planului. Investiția trebuie menținută activă timp de 3 ani (IMM) sau 5 ani (întreprinderi mari).',
            'placeholder' => 'Ministerul verifică periodic dacă proiectul funcționează...',
        ),
        array(
            'key' => 'field_ap_step8_note_label',
            'label' => 'Pasul 8: Etichetă notă',
            'name' => 'ap_step8_note_label',
            'type' => 'text',
            'required' => 0,
            'default_value' => 'Monitorizare:',
            'placeholder' => 'Monitorizare:',
        ),
        array(
            'key' => 'field_ap_step8_note_text',
            'label' => 'Pasul 8: Text notă',
            'name' => 'ap_step8_note_text',
            'type' => 'textarea',
            'rows' => 2,
            'new_lines' => 'wpautop',
            'required' => 0,
            'default_value' => 'Rapoarte periodice și vizite de verificare',
            'placeholder' => 'Rapoarte periodice și vizite de verificare',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_type',
                'operator' => '==',
                'value' => 'front_page',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Câmpuri pentru secțiunea "Procedura de aplicare" (bloc stânga) pe pagină.',
));

endif;
?>
