<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_eligible_sectors_fields',
        'title' => 'Sectoare eligibile',
        'fields' => array(
            array(
                'key' => 'field_eligible_sector_heading',
                'label' => 'Antet sectoare',
                'name' => 'eligible_sector_heading',
                'type' => 'text',
                'instructions' => 'Introduceți antetul secțiunii pentru sectoare eligibile.',
                'required' => 1,
                'default_value' => 'Sectoare eligibile',
                'placeholder' => 'Sectoare eligibile',
            ),
            array(
                'key' => 'field_eligible_sector_description',
                'label' => 'Descriere sectoare',
                'name' => 'eligible_sector_description',
                'type' => 'textarea',
                'instructions' => 'Introduceți descrierea pentru secțiunea sectoare eligibile.',
                'required' => 1,
                'default_value' => 'Programul sprijină investițiile în șase ramuri industriale strategice, esențiale pentru modernizarea economiei Republicii Moldova:',
                'placeholder' => 'Programul sprijină investițiile...',
            ),
            // Sectorul 1: Industria electronică
            array(
                'key' => 'field_sector_1_name',
                'label' => 'Numele sectorului 1',
                'name' => 'sector_1_name',
                'type' => 'text',
                'default_value' => 'Industria electronică',
                'instructions' => 'Introduceți numele pentru primul sector.',
            ),
            array(
                'key' => 'field_sector_1_description',
                'label' => 'Descrierea sectorului 1',
                'name' => 'sector_1_description',
                'type' => 'textarea',
                'default_value' => 'Componente electronice, echipamente IT, sisteme automatizate',
                'instructions' => 'Introduceți o descriere pentru primul sector.',
            ),
            array(
                'key' => 'field_sector_1_icon',
                'label' => 'Icoana sectorului 1',
                'name' => 'sector_1_icon',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'instructions' => 'Încărcați imaginea pentru primul sector.',
            ),
            // Sectorul 2: Industria chimică
            array(
                'key' => 'field_sector_2_name',
                'label' => 'Numele sectorului 2',
                'name' => 'sector_2_name',
                'type' => 'text',
                'default_value' => 'Industria chimică și farmaceutică',
                'instructions' => 'Introduceți numele pentru al doilea sector.',
            ),
            array(
                'key' => 'field_sector_2_description',
                'label' => 'Descrierea sectorului 2',
                'name' => 'sector_2_description',
                'type' => 'textarea',
                'default_value' => 'Medicamente, produse chimice, cosmetice, materiale sanitare',
                'instructions' => 'Introduceți o descriere pentru al doilea sector.',
            ),
            array(
                'key' => 'field_sector_2_icon',
                'label' => 'Icoana sectorului 2',
                'name' => 'sector_2_icon',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'instructions' => 'Încărcați imaginea pentru al doilea sector.',
            ),
            // Sectorul 3: Mașini și componente auto
            array(
                'key' => 'field_sector_3_name',
                'label' => 'Numele sectorului 3',
                'name' => 'sector_3_name',
                'type' => 'text',
                'default_value' => 'Industria constructoare de mașini și componente auto',
                'instructions' => 'Introduceți numele pentru al treilea sector.',
            ),
            array(
                'key' => 'field_sector_3_description',
                'label' => 'Descrierea sectorului 3',
                'name' => 'sector_3_description',
                'type' => 'textarea',
                'default_value' => 'Piese auto, echipamente industriale, utilaje agricole',
                'instructions' => 'Introduceți o descriere pentru al treilea sector.',
            ),
            array(
                'key' => 'field_sector_3_icon',
                'label' => 'Icoana sectorului 3',
                'name' => 'sector_3_icon',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'instructions' => 'Încărcați imaginea pentru al treilea sector.',
            ),
            // Sectorul 4: Textilă și de îmbrăcăminte
            array(
                'key' => 'field_sector_4_name',
                'label' => 'Numele sectorului 4',
                'name' => 'sector_4_name',
                'type' => 'text',
                'default_value' => 'Industria textilă și de îmbrăcăminte',
                'instructions' => 'Introduceți numele pentru al patrulea sector.',
            ),
            array(
                'key' => 'field_sector_4_description',
                'label' => 'Descrierea sectorului 4',
                'name' => 'sector_4_description',
                'type' => 'textarea',
                'default_value' => 'Confecții textile, materiale tehnice, accesorii vestimentare',
                'instructions' => 'Introduceți o descriere pentru al patrulea sector.',
            ),
            array(
                'key' => 'field_sector_4_icon',
                'label' => 'Icoana sectorului 4',
                'name' => 'sector_4_icon',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'instructions' => 'Încărcați imaginea pentru al patrulea sector.',
            ),
            // Sectorul 5: Materiale de construcții
            array(
                'key' => 'field_sector_5_name',
                'label' => 'Numele sectorului 5',
                'name' => 'sector_5_name',
                'type' => 'text',
                'default_value' => 'Industria materialelor de construcții',
                'instructions' => 'Introduceți numele pentru al cincilea sector.',
            ),
            array(
                'key' => 'field_sector_5_description',
                'label' => 'Descrierea sectorului 5',
                'name' => 'sector_5_description',
                'type' => 'textarea',
                'default_value' => 'Materiale de construcție, elemente prefabricate, sisteme de izolație',
                'instructions' => 'Introduceți o descriere pentru al cincilea sector.',
            ),
            array(
                'key' => 'field_sector_5_icon',
                'label' => 'Icoana sectorului 5',
                'name' => 'sector_5_icon',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'instructions' => 'Încărcați imaginea pentru al cincilea sector.',
            ),
            // Sectorul 6: Industria alimentară
            array(
                'key' => 'field_sector_6_name',
                'label' => 'Numele sectorului 6',
                'name' => 'sector_6_name',
                'type' => 'text',
                'default_value' => 'Industria alimentară',
                'instructions' => 'Introduceți numele pentru al șaselea sector.',
            ),
            array(
                'key' => 'field_sector_6_description',
                'label' => 'Descrierea sectorului 6',
                'name' => 'sector_6_description',
                'type' => 'textarea',
                'default_value' => 'Procesarea alimentelor, băuturi, conserve, produse bio',
                'instructions' => 'Introduceți o descriere pentru al șaselea sector.',
            ),
            array(
                'key' => 'field_sector_6_icon',
                'label' => 'Icoana sectorului 6',
                'name' => 'sector_6_icon',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'instructions' => 'Încărcați imaginea pentru al șaselea sector.',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_type',
                    'operator' => '==',
                    'value' => 'front_page',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

endif;
?>