<?php
/**
 * Înregistrează câmpurile ACF pentru secțiunea "Istorii de succes"
 * (Success Stories)
 *
 * Creat pentru versiunea GRATUITĂ a ACF.
 * Toate câmpurile au default_value, unde este cazul.
 */
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_success_story_fields',
    'title' => 'Istorie de succes (RO & EN)',
    'fields' => array(
        // --- Informații de bază pentru card (tile) - ROMÂNĂ ---
        array(
            'key' => 'field_ss_info_heading_ro',
            'label' => 'Informații de bază (RO)',
            'name' => '',
            'type' => 'message',
            'message' => 'Configurați informațiile pentru versiunea în limba română.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ss_tittle_company',
            'label' => 'Numele companiei (RO)',
            'name' => 'tittle_company',
            'type' => 'text',
            'instructions' => 'Introduceți numele complet al companiei în limba română.',
            'required' => 1,
            'placeholder' => 'Numele Companiei SRL',
        ),
        array(
            'key' => 'field_ss_sector',
            'label' => 'Domeniul de activitate (RO)',
            'name' => 'sector',
            'type' => 'text',
            'instructions' => 'Introduceți sectorul în care activează compania în limba română.',
            'required' => 0,
            'placeholder' => 'Industria prelucrătoare, IT, etc.',
        ),
        array(
            'key' => 'field_ss_description',
            'label' => 'Descriere scurtă (RO)',
            'name' => 'description',
            'type' => 'textarea',
            'instructions' => 'Introduceți o descriere scurtă în limba română, vizibilă pe cardul principal.',
            'required' => 0,
            'rows' => 3,
            'new_lines' => 'wpautop',
            'placeholder' => 'Compania a beneficiat de ajutorul de stat pentru a-și extinde capacitatea de producție...',
        ),
        array(
            'key' => 'field_ss_support_percent',
            'label' => 'Procent sprijin',
            'name' => 'support_percenеnt',
            'type' => 'number',
            'instructions' => 'Introduceți procentul de sprijin acordat (ex: 25). Acest câmp nu se traduce.',
            'required' => 0,
            'min' => 0,
            'max' => 100,
            'placeholder' => '25',
        ),
        // --- Informații de bază pentru card (tile) - ENGLEZĂ ---
        array(
            'key' => 'field_ss_info_heading_en',
            'label' => 'Informații de bază (EN)',
            'name' => '',
            'type' => 'message',
            'message' => 'Configurați informațiile pentru versiunea în limba engleză.',
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_ss_tittle_company_en',
            'label' => 'Numele companiei (EN)',
            'name' => 'tittle_company_en',
            'type' => 'text',
            'instructions' => 'Introduceți numele complet al companiei în limba engleză.',
            'required' => 0,
            'placeholder' => 'Company Name LTD',
        ),
        array(
            'key' => 'field_ss_sector_en',
            'label' => 'Domeniul de activitate (EN)',
            'name' => 'sector_en',
            'type' => 'text',
            'instructions' => 'Introduceți sectorul în care activează compania în limba engleză.',
            'required' => 0,
            'placeholder' => 'Manufacturing, IT, etc.',
        ),
        array(
            'key' => 'field_ss_description_en',
            'label' => 'Descriere scurtă (EN)',
            'name' => 'description_en',
            'type' => 'textarea',
            'instructions' => 'Introduceți o descriere scurtă în limba engleză, vizibilă pe cardul principal.',
            'required' => 0,
            'rows' => 3,
            'new_lines' => 'wpautop',
            'placeholder' => 'The company benefited from state aid to expand its production capacity...',
        ),
        // --- Informații pentru pop-up - ROMÂNĂ ---
        array(
            'key' => 'field_ss_popup_heading_ro',
            'label' => 'Informații detaliate (RO)',
            'name' => '',
            'type' => 'message',
            'message' => 'Aceste câmpuri vor fi afișate în fereastra pop-up (RO).',
            'new_lines' => 'wpautop',
        ),
       array(
            'key' => 'field_ss_full_story_description',
            'label' => 'Descriere sub numele companiei (RO)',
            'name' => 'full_story_description',
            'type' => 'textarea',
            'instructions' => 'Introduceți o scurtă descriere a companiei în limba română pentru a fi afișată sub numele acesteia în fereastra pop-up.',
            'required' => 0,
            'rows' => 3,
            'new_lines' => 'wpautop',
            'placeholder' => 'Compania noastră se angajează să ofere servicii de înaltă calitate...',
        ),
        array(
            'key' => 'field_ss_quote',
            'label' => 'Citat de la companie (RO)',
            'name' => 'quote',
            'type' => 'textarea',
            'instructions' => 'Introduceți o scurtă citat de la reprezentantul companiei în limba română.',
            'required' => 0,
            'rows' => 3,
            'new_lines' => 'wpautop',
            'placeholder' => '"Fără sprijinul de stat, nu am fi putut realiza această investiție în ritmul dorit."',
        ),
        
        array(
            'key' => 'field_ss_investment',
            'label' => 'Investiție totală (M MDL)',
            'name' => 'investment',
            'type' => 'number',
            'instructions' => 'Introduceți valoarea totală a investiției (în milioane MDL). Acest câmp nu se traduce.',
            'required' => 0,
            'placeholder' => '1.5',
        ),
        array(
            'key' => 'field_ss_jobs',
            'label' => 'Număr de locuri de muncă',
            'name' => 'jobs',
            'type' => 'number',
            'instructions' => 'Introduceți numărul de locuri de muncă nou create. Acest câmp nu se traduce.',
            'required' => 0,
            'placeholder' => '25',
        ),
        array(
            'key' => 'field_ss_aid_granted',
            'label' => 'Ajutor de stat acordat (M MDL)',
            'name' => 'aid_granted',
            'type' => 'number',
            'instructions' => 'Introduceți valoarea ajutorului de stat acordat (în milioane MDL). Acest câmp nu se traduce.',
            'required' => 0,
            'placeholder' => '0.5',
        ),
        // --- Informații pentru pop-up - ENGLEZĂ ---
        array(
            'key' => 'field_ss_popup_heading_en',
            'label' => 'Informații detaliate (EN)',
            'name' => '',
            'type' => 'message',
            'message' => 'Aceste câmpuri vor fi afișate în fereastra pop-up (EN).',
            'new_lines' => 'wpautop',
        ),
       array(
            'key' => 'field_ss_full_story_description_en',
            'label' => 'Descriere sub numele companiei (EN)',
            'name' => 'full_story_description_en',
            'type' => 'textarea',
            'instructions' => 'Introduceți o scurtă descriere a companiei în limba engleză pentru a fi afișată sub numele acesteia în fereastra pop-up.',
            'required' => 0,
            'rows' => 3,
            'new_lines' => 'wpautop',
            'placeholder' => 'Our company is committed to providing high-quality services...',
        ),
        array(
            'key' => 'field_ss_quote_en',
            'label' => 'Citat de la companie (EN)',
            'name' => 'quote_en',
            'type' => 'textarea',
            'instructions' => 'Introduceți o scurtă citat de la reprezentantul companiei în limba engleză.',
            'required' => 0,
            'rows' => 3,
            'new_lines' => 'wpautop',
            'placeholder' => '"Without state support, we would not have been able to make this investment at the desired pace."',
        ),
        array(
            'key' => 'field_ss_full_story',
            'label' => 'Istoria completă',
            'name' => 'full_story',
            'type' => 'wysiwyg',
            'instructions' => 'Introduceți textul complet al istoriei de succes. Poate conține formatare (liste, bold, etc.).',
            'required' => 0,
            'media_buttons' => 1,
        ),
        
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'success_story',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'permalink',
        1 => 'the_content',
        2 => 'excerpt',
        3 => 'discussion',
        4 => 'comments',
        5 => 'revisions',
        6 => 'slug',
        7 => 'author',
        8 => 'format',
        9 => 'page_attributes',
        10 => 'featured_image',
        11 => 'categories',
        12 => 'tags',
        13 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => 'Câmpuri personalizate pentru tipul de post "Istorie de succes".',
));

endif;